### PR TITLE
Improved the rows webui, issue #277

### PR DESCRIPTION
**Pull request by toadmengo**
Solved Issue #277

In the layout, I removed the sidebar, leaving the links at the top of the page. The Rows page is the default page, and improvements were made to Rows:

Instead of a delete button, the user selects a checkbox of the row, and selects delete on the action then submits the action.
More actions can be added in the future (potentially, users could modify data in the rows from sync-endpoint?)

Also, I haven't used the RowOutcomeList fully, and not sure how I should display RowOutcome results to the client.

Let me know if there are any issues or the code needs to be cleaned up more.

### CODE REVIEW

**Comment by toadmengo** [comment]
I restricted access to the any of the /tables, by requiring ROLE_ADMINISTER_TABLES or ROLE_SITE_ADMIN to access the site. 
I did it through the SecurityConfig class, so I had to change the ExceptionHandler to redirect back to the default "/" URL when there is a denied access. It still redirects to "/login?error" if there is an invalid login attempt, but now if you attempt to access any table without the right roles you'll simply stay on the page you're in.

Also, the landing page only links to the tables if you are an admin.

I'm sure there's a slightly better way to do use SecurityConfig but I don't completely understand this part of Spring super well.

Let me know if there are any problems with this!

**Comment by toadmengo** [comment]
Also, I noticed the export page doesn't export data. Was it like this before?

**Comment by wbrunette** [comment]
@toadmengo the export page used to work; however, changes have been made since the last release. Would you mind looking into it?

**Comment by toadmengo** [comment]
I ran into the same issues using the master branch (export didn't work for either format). Would it be appropriate to create another issue for it?

**Comment by wbrunette** [comment]
@toadmengo. Yes create another issue.

**Pull request merged**
