### PR TITLE
Fix: ODK version updated in template.

### PR DESCRIPTION
**Pull request by adityaofficial10**
Fixes issue: https://github.com/odk-x/tool-suite-X/issues/187

**What changes have been made?**
- The version has been updated to X in web UI login screen.

### CODE REVIEW

**Comment by adityaofficial10** [comment]
@linl33 
Kindly review this.

**Comment by linl33** [comment]
Could you change it to ODK-X instead? i.e. ~~Open Data Kit 2.0~~ ODK-X.
Otherwise it looks good. Thank you!

**Comment by adityaofficial10** [comment]
@linl33 
Sure, I'll do the  needful.
Thanks for the review.

**Comment by adityaofficial10** [comment]
@linl33 
I've made the required changes.

**Comment by wbrunette** [comment]
added development branch to match release process

**Review by wbrunette — APPROVED** [review]

**Pull request merged**
